version: '3.9'
services:
  cypress:
    build:
      context: ./cypress-docker/
      dockerfile: Dockerfile
    volumes:
      - .:/e2e
      - node_modules:/e2e/node_modules
      - cache:/root/.cache/
    working_dir: /e2e
    entrypoint: bash -c "yarn install && yarn exec cypress install && yarn run cypress"
  cypress-update-screenshot:
    build:
      context: ./cypress-docker/
      dockerfile: Dockerfile
    volumes:
      - .:/e2e
      - node_modules:/e2e/node_modules
      - cache:/root/.cache/
    working_dir: /e2e
    entrypoint: bash -c "yarn install && yarn exec cypress install && yarn run cypress:update-screenshot"
volumes:
  node_modules: {}
  cache: {}
