import { Inter } from 'next/font/google'
import StyledComponentsRegistry from 'components/styled/StyledComponentsRegistry'
import { RecoilRoot } from 'recoil'
import { ColneAppWithLayout } from 'components/common/ColneAppWithLayout'
import { getCurrentUser } from 'api-client/user'
import { getCSRFToken } from 'api-client/common'
import { headers } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser(headers())
  const csrfToken = await getCSRFToken(headers())

  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <RecoilRoot>
            <ColneAppWithLayout user={currentUser} csrfToken={csrfToken}>
              {children}
            </ColneAppWithLayout>
          </RecoilRoot>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
