name: Cypress
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/included:12.17.1
    steps:
      - uses: actions/checkout@v3
      - name: Install fonts
        run: apt-get update && apt-get install -y fonts-noto-cjk
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn install
      - run: yarn run cypress
